apiVersion: v1
kind: Service
metadata:
  name: python-volume-service
spec:
  selector:
    app: python-volume-example
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort  # You can change the service type as needed